version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    environment:
      - CAT_API_KEY=<put-your-api-key>
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'